### ISSUE TITLE
Alerts Sensor Broken

### ISSUE THREAD

**Issue by RaptahJezus** [alexander0042/pirate-weather-ha#38]
Hello,

We had a severe fog advisory issued in our area today (Philadelphia, PA). It seems there's an issue pulling this data into the pirateweather alerts sensor. 

Here's the relevant portion of home-assistant.log:

```
2022-02-03 16:30:20 ERROR (MainThread) [homeassistant.components.sensor] pirateweather: Error on device update!
Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/forecastio/models.py", line 121, in __getattr__
    return self.json[name]
KeyError: 'description'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity_platform.py", line 431, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/srv/homeassistant/lib/python3.9/site-packages/homeassistant/helpers/entity.py", line 684, in async_device_update
    await task
  File "/usr/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/lxc-data/homeassistant/custom_components/pirateweather/sensor.py", line 758, in update
    self._state = self.get_state(alerts)
  File "/lxc-data/homeassistant/custom_components/pirateweather/sensor.py", line 778, in get_state
    alerts[dkey] = getattr(alert, attr)
  File "/srv/homeassistant/lib/python3.9/site-packages/forecastio/models.py", line 123, in __getattr__
    raise PropertyUnavailable(
forecastio.utils.PropertyUnavailable: Property 'description' is not valid or is not available for this forecast
```

For comparison, the Dark Sky alerts sensor returned a state of '1', and the following attributes:
```
time: 1643913180
description: ...DENSE FOG ADVISORY IN EFFECT UNTIL 9 PM EST THIS EVENING... * WHAT...Visibility one quarter mile or less in patchy dense fog. * WHERE...Portions of central, northern and northwest New Jersey and east central, northeast and southeast Pennsylvania. * WHEN...Until 9 PM EST this evening. * IMPACTS...Hazardous driving conditions due to low visibility.

expires: 1643940000
severity: advisory
uri: https://alerts.weather.gov/cap/wwacapget.php?x=PA1263E2072CC4.DenseFogAdvisory.1263E213F120PA.PHINPWPHI.c652b4d1897352f60f68d73e00327f21
regions: Berks, Carbon, Delaware, Eastern Chester, Eastern Montgomery, Lehigh, Lower Bucks, Monroe, Northampton, Philadelphia, Upper Bucks, Western Chester, Western Montgomery
title: Dense Fog Advisory
icon: mdi:alert-circle
friendly_name: Dark Sky Alerts
```

**EDIT**

I tried querying both DarkSky's API and PirateWeather's API directly to see what kind of results I got. Dark Sky returned: 

```
"alerts":[{"title":"Dense Fog Advisory","regions":["Berks","Carbon","Delaware","Eastern Chester","Eastern Montgomery","Lehigh","Lower Bucks","Monroe","Northampton","Philadelphia","Upper Bucks","Western Chester","Western Montgomery"],"severity":"advisory","time":1643913180,"expires":1643940000,"description":"...DENSE FOG ADVISORY IN EFFECT UNTIL 9 PM EST THIS EVENING... * WHAT...Visibility one quarter mile or less in patchy dense fog. * WHERE...Portions of central, northern and northwest New Jersey and east central, northeast and southeast Pennsylvania. * WHEN...Until 9 PM EST this evening. * IMPACTS...Hazardous driving conditions due to low visibility.\n","uri":"https://alerts.weather.gov/cap/wwacapget.php?x=PA1263E2072CC4.DenseFogAdvisory.1263E213F120PA.PHINPWPHI.c652b4d1897352f60f68d73e00327f21"}]
```

PirateWeather seems to only return

```
"alerts": [{"title": "Dense Fog", "time": 1643913180, "expires": 1643940000, "significance": "Advisory"}]
```

I'm guessing the lack of uri/description is breaking the call to forcastio

**Comment by alexander0042** [comment]
Hi,

Thanks for catching this! Because I only have alerts working for the US right now, it's hard for me to catch these things, so I really appreciate it. 
The HA sensor code is pretty picky, so needs the API results to be in the exact Dark Sky form (which is the goal of Pirate Weather). I made a small tweak to the response format, and I believe the Alert integration is working now.

You'll notice that it's missing a few variables (notably the description) that are present in Dark Sky. This is a known right now, since I'm relying on an overview of the (warning database)[https://mesonet.agron.iastate.edu/request/gis/watchwarn.phtml] that includes shape files to produce this. I don't particularly like this approach, since it's limited to the US and doesn't have detailed descriptions, but it's what's working at the moment. Hopefully I can create a grid based dateset to use at some point in the future though

**Comment by RaptahJezus** [comment]
Looks good, as a test I updated my home coordinates to somewhere with a currently active winter weather advisory and it picked it up. Will definitely look forward to additional info in the alerts!

Thanks for all your time on this project.
